global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ordering-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - iam:3001
          - notification:3002
          - recommendation:3003
          - billing:3004
          - appeal-admin:3005
